name: CMake
on: [push, pull_request]
env:
  BUILD_TYPE: Release
  VST_TARGET_NAME: PeakEater_VST3
  JUCE_REVISION: cc9fdc3d6
  FF_METERS_REVISION: 71e05b8
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Init Git Submodules
        run: git submodule update --init --recursive
      - name: Checkout JUCE
        run: cd ${{github.workspace}}/Dependencies/JUCE && git checkout ${{env.JUCE_REVISION}}
      - name: Checkout ff_meters
        run: cd ${{github.workspace}}/Dependencies/ff_meters && git checkout ${{env.FF_METERS_REVISION}}
      - name: Run CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DJUCE_BUILD_EXAMPLES=OFF -DJUCE_BUILD_EXTRAS=ON
      - name: Build VST3
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ${{env.VST_TARGET_NAME}}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MacOS-PeakEater.vst3
          path: ${{github.workspace}}/build/PeakEater_artefacts/Release/VST3/PeakEater.vst3

  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Init Git Submodules
        run: git submodule update --init --recursive
      - name: Checkout JUCE
        run: cd ${{github.workspace}}/Dependencies/JUCE && git checkout ${{env.JUCE_REVISION}}
      - name: Checkout ff_meters
        run: cd ${{github.workspace}}/Dependencies/ff_meters && git checkout ${{env.FF_METERS_REVISION}}
      - name: Patch ff_meters
        run: sed -i '' '/#warning/d' ${{github.workspace}}/Dependencies/ff_meters/LevelMeter/LevelMeterSource.h
      - name: Run CMake
        run: cmake -B ${{github.workspace}}/build -G "Visual Studio 16 2019" -T "v140" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DJUCE_BUILD_EXAMPLES=OFF -DJUCE_BUILD_EXTRAS=ON
      - name: Build VST3
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ${{env.VST_TARGET_NAME}}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Windows-PeakEater.vst3
          path: ${{github.workspace}}/build/PeakEater_artefacts/Release/VST3/PeakEater.vst3/Contents/x86_64-win/PeakEater.vst3
