name: Execute nmerger checks
run-name: 'Merge checks for PR #${{ github.event.number }}'
on: pull_request
env:
  BUILD_TYPE: Release
  VST_TARGET_NAME: PeakEater_VST3
  AU_TARGET_NAME: PeakEater_AU
  LV2_TARGET_NAME: PeakEater_LV2
  CLAP_TARGET_NAME: PeakEater_CLAP
  JUCE_REVISION: 4e68af7
  VERSION: 0.3.5
  BUILD_ID: '${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}'
jobs:
  macos:
    name: macOS
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/setup-node@v3
        with:
          node-version: 18.11
      - run: |
          echo $PATH
          python --version
          which python
          node --version
          which node
          npm --version
          which npm
      - name: Install Python Dependencies
        run: python -m pip install -r ${{github.workspace}}/requirements.txt 
      - name: Init Git Submodules
        run: git submodule update --init --recursive
      - name: Checkout JUCE
        run: cd ${{github.workspace}}/Dependencies/JUCE && git checkout ${{env.JUCE_REVISION}}
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DJUCE_BUILD_EXAMPLES=OFF -DJUCE_BUILD_EXTRAS=ON
      - name: Build VST3
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ${{env.VST_TARGET_NAME}}
      - name: Build AU
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ${{env.AU_TARGET_NAME}}
      - name: Build CLAP
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ${{env.CLAP_TARGET_NAME}}
      - name: Build LV2
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ${{env.LV2_TARGET_NAME}}
      - name: Package
        run: python ${{github.workspace}}/Scripts/Release/MacOS.py --release_type=${{env.BUILD_TYPE}}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PeakEater_v${{env.VERSION}}_macOS_${{env.BUILD_ID}}
          path: ${{github.workspace}}/build/release/PeakEater.dmg

  windows:
    name: Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Init Git Submodules
        run: git submodule update --init --recursive
      - name: Checkout JUCE
        run: cd ${{github.workspace}}\Dependencies\JUCE && git checkout ${{env.JUCE_REVISION}}
      - name: Configure CMake 
        run: cmake . -B ${{github.workspace}}\build -G 'Visual Studio 17 2022' -A x64 -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DJUCE_BUILD_EXAMPLES=OFF -DJUCE_BUILD_EXTRAS=ON
      - name: Build VST3
        run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}} --target ${{env.VST_TARGET_NAME}}
      - name: Build CLAP
        run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}} --target ${{env.CLAP_TARGET_NAME}}
      - name: Build LV2
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ${{env.LV2_TARGET_NAME}}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PeakEater_v${{env.VERSION}}_Windows_${{env.BUILD_ID}}
          path: |
            build\PeakEater_artefacts\${{env.BUILD_TYPE}}\VST3\PeakEater.vst3\Contents\x86_64-win\PeakEater.vst3
            build\PeakEater_artefacts\${{env.BUILD_TYPE}}\LV2\PeakEater.lv2
            build\PeakEater_artefacts\${{env.BUILD_TYPE}}\CLAP\PeakEater.clap

  linux:
    name: Linux
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Init Git Submodules
        run: git submodule update --init --recursive
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ libgtk-3-dev libfreetype6-dev libx11-dev libxinerama-dev libxrandr-dev libxcursor-dev mesa-common-dev libasound2-dev freeglut3-dev libxcomposite-dev libcurl4-openssl-dev
          sudo apt-get install libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-dev
      - name: Checkout JUCE
        run: cd ${{github.workspace}}/Dependencies/JUCE && git checkout ${{env.JUCE_REVISION}}
      - name: Configure CMake 
        run: cmake . -B ${{github.workspace}}/build -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DJUCE_BUILD_EXAMPLES=OFF -DJUCE_BUILD_EXTRAS=ON
      - name: Build VST3
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ${{env.VST_TARGET_NAME}}
      - name: Build CLAP
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ${{env.CLAP_TARGET_NAME}}
      - name: Build LV2
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ${{env.LV2_TARGET_NAME}}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PeakEater_v${{env.VERSION}}_Linux_${{env.BUILD_ID}}
          path: |
            build/PeakEater_artefacts/VST3/PeakEater.vst3/Contents/x86_64-linux/PeakEater.so
            build/PeakEater_artefacts/LV2/PeakEater.lv2
            build/PeakEater_artefacts/CLAP/PeakEater.clap
