name: Ensure PR is ready to me merged
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets:
      MACOS_BUILD_CERTIFICATE_BASE64: ${{ secrets.MACOS_BUILD_CERTIFICATE_BASE64 }}
      MACOS_P12_PASSWORD: ${{ secrets.MACOS_P12_PASSWORD }}
      MACOS_BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.MACOS_BUILD_PROVISION_PROFILE_BASE64 }}
      MACOS_KEYCHAIN_PASSWORD: ${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
      MACOS_APPLE_ID: ${{ secrets.MACOS_APPLE_ID }}
      MACOS_APPLE_PASSWORD: ${{ secrets.MACOS_APPLE_PASSWORD }}
      MACOS_APPLE_TEAM_ID: ${{ secrets.MACOS_APPLE_TEAM_ID }}
      MACOS_APPLE_IDENTITY: ${{ secrets.MACOS_APPLE_IDENTITY }}
