name: Execute nmerger checks
run-name: "Merge checks for PR #${{ github.event.number }}"
on: pull_request

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets:
      MACOS_BUILD_CERTIFICATE_BASE64: ${{ secrets.MACOS_BUILD_CERTIFICATE_BASE64 }}
      MACOS_BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.MACOS_BUILD_PROVISION_PROFILE_BASE64 }}
      MACOS_KEYCHAIN_PASSWORDMACOS_APPLE_IDENTITY: ${{ secrets.MACOS_KEYCHAIN_PASSWORDMACOS_APPLE_IDENTITY }}
      MACOS_APPLE_IDENTITY: ${{ secrets.MACOS_APPLE_IDENTITY }}
      MACOS_APPLE_ID: ${{ secrets.MACOS_APPLE_ID }}
      MACOS_APPLE_PASSWORD: ${{ secrets.MACOS_APPLE_PASSWORD }}
      MACOS_APPLE_TEAM_ID: ${{ secrets.MACOS_APPLE_TEAM_ID }}
