name: Create release draft
on: pull_request

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets:
      MACOS_BUILD_CERTIFICATE_BASE64: ${{ secrets.MACOS_BUILD_CERTIFICATE_BASE64 }}
      MACOS_P12_PASSWORD: ${{ secrets.MACOS_P12_PASSWORD }}
      MACOS_BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.MACOS_BUILD_PROVISION_PROFILE_BASE64 }}
      MACOS_KEYCHAIN_PASSWORD: ${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
      MACOS_APPLE_ID: ${{ secrets.MACOS_APPLE_ID }}
      MACOS_APPLE_PASSWORD: ${{ secrets.MACOS_APPLE_PASSWORD }}
      MACOS_APPLE_TEAM_ID: ${{ secrets.MACOS_APPLE_TEAM_ID }}
      MACOS_APPLE_IDENTITY: ${{ secrets.MACOS_APPLE_IDENTITY }}

  release:
    name: Publish Release Draft
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Download macOS Artifacts
        uses: actions/download-artifact@v3
        with:
          name: macos
          path: macos
      - name: Download Windows Artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows
          path: windows
      - name: Download Linux Artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux
          path: linux
      - name: Archive Artifacts
        run: |
          zip -r macos{.zip,}
          mkdir windows/tmp
          mv windows/VST3/PeakEater.vst3/Contents/x86_64-win/PeakEater.vst3 windows/tmp
          rm -rf windows/VST3/PeakEater.vst3
          mv windows/tmp/PeakEater.vst3 windows/VST3
          rm -rf windows/tmp
          zip -r windows{.zip,}
          zip -r linux{.zip,}
      - id: get-version
        run: |
          version=$( conan inspect . --format json | jq '.version' )
          echo "::set-output name=version::$version"
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          removeArtifacts: true
          makeLatest: true
          tag: "v${{ steps.get-version.outputs.version }}"
          artifacts: "macos.zip,windows.zip,linux.zip"
