name: Create release draft
on: pull_request

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets:
      MACOS_BUILD_CERTIFICATE_BASE64: ${{ secrets.MACOS_BUILD_CERTIFICATE_BASE64 }}
      MACOS_P12_PASSWORD: ${{ secrets.MACOS_P12_PASSWORD }}
      MACOS_BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.MACOS_BUILD_PROVISION_PROFILE_BASE64 }}
      MACOS_KEYCHAIN_PASSWORD: ${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
      MACOS_APPLE_ID: ${{ secrets.MACOS_APPLE_ID }}
      MACOS_APPLE_PASSWORD: ${{ secrets.MACOS_APPLE_PASSWORD }}
      MACOS_APPLE_TEAM_ID: ${{ secrets.MACOS_APPLE_TEAM_ID }}
      MACOS_APPLE_IDENTITY: ${{ secrets.MACOS_APPLE_IDENTITY }}

  release:
    name: Bundle & publish release draft
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          sudo apt-get install jq
          pip3 install conan==2.0.4
      - id: get-version
        run: |
          version=$( conan inspect . --format json | jq '.version' )
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Download macOS Artifacts
        uses: actions/download-artifact@v3
        with:
          name: macos
          path: peakeater-macOS-${{ steps.get-version.outputs.version }}-universal.zip
      - name: Download Windows Artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows
          path: peakeater-Windows-${{ steps.get-version.outputs.version }}-x86_64.zip
      - name: Download Linux Artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux
          path: peakeater-linux-${{ steps.get-version.outputs.version }}-x86_64.zip
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          removeArtifacts: true
          makeLatest: true
          tag: "v${{ steps.get-version.outputs.version }}"
          artifacts: "peakeater-macOS-${{ steps.get-version.outputs.version }}-universal.zip,peakeater-Windows-${{ steps.get-version.outputs.version }}-x86_64.zip,peakeater-linux-${{ steps.get-version.outputs.version }}-x86_64.zip"
