name: Create release draft
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets:
      MACOS_BUILD_CERTIFICATE_BASE64: ${{ secrets.MACOS_BUILD_CERTIFICATE_BASE64 }}
      MACOS_P12_PASSWORD: ${{ secrets.MACOS_P12_PASSWORD }}
      MACOS_BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.MACOS_BUILD_PROVISION_PROFILE_BASE64 }}
      MACOS_KEYCHAIN_PASSWORD: ${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
      MACOS_APPLE_ID: ${{ secrets.MACOS_APPLE_ID }}
      MACOS_APPLE_PASSWORD: ${{ secrets.MACOS_APPLE_PASSWORD }}
      MACOS_APPLE_TEAM_ID: ${{ secrets.MACOS_APPLE_TEAM_ID }}
      MACOS_APPLE_IDENTITY: ${{ secrets.MACOS_APPLE_IDENTITY }}

  release:
    name: Release
    runs-on: ubuntu-22.04
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Download macOS build
        uses: actions/download-artifact@v3
        with:
          name: macos
          path: release
      - name: Download Windows build
        uses: actions/download-artifact@v3
        with:
          name: windows
          path: release
      - name: Download Linux build
        uses: actions/download-artifact@v3
        with:
          name: linux
          path: release
      - name: Get release version
        id: get-version
        run: |
          sudo apt-get install jq
          pip3 install conan==2.0.4
          version=$( conan inspect . --format json | jq -r '.version' )
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Create release draft
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          removeArtifacts: true
          makeLatest: true
          tag: "v${{ steps.get-version.outputs.version }}"
          artifacts: "release/*"
